CREATE TABLE categories (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO categories (name) VALUES
    ('Acesso'),
    ('Hardware'),
    ('Software'),
    ('Financeiro'),
    ('Outros');
