CREATE TABLE tickets (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title                VARCHAR(120)  NOT NULL,
    description          VARCHAR(5000) NOT NULL,
    priority             VARCHAR(20)   NOT NULL,
    status               VARCHAR(30)   NOT NULL,
    category_id          BIGINT        NOT NULL REFERENCES categories (id),
    requester_id         BIGINT        NOT NULL REFERENCES users (id),
    assignee_id          BIGINT        REFERENCES users (id),
    created_at           TIMESTAMPTZ   NOT NULL,
    due_at               TIMESTAMPTZ   NOT NULL,
    paused_at            TIMESTAMPTZ,
    paused_total_seconds BIGINT        NOT NULL DEFAULT 0,
    resolved_at          TIMESTAMPTZ,
    sla_breached         BOOLEAN,
    version              BIGINT        NOT NULL DEFAULT 0
);

CREATE INDEX idx_tickets_status_due_at ON tickets (status, due_at);
CREATE INDEX idx_tickets_requester ON tickets (requester_id);
CREATE INDEX idx_tickets_assignee ON tickets (assignee_id);

CREATE TABLE ticket_history (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id   BIGINT       NOT NULL REFERENCES tickets (id) ON DELETE CASCADE,
    actor_id    BIGINT       NOT NULL REFERENCES users (id),
    occurred_at TIMESTAMPTZ  NOT NULL,
    event_type  VARCHAR(30)  NOT NULL,
    field       VARCHAR(30),
    old_value   VARCHAR(255),
    new_value   VARCHAR(255)
);

CREATE INDEX idx_ticket_history_ticket ON ticket_history (ticket_id, occurred_at);
