CREATE TABLE comments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id  BIGINT        NOT NULL REFERENCES tickets (id) ON DELETE CASCADE,
    author_id  BIGINT        NOT NULL REFERENCES users (id),
    text       VARCHAR(5000) NOT NULL,
    created_at TIMESTAMPTZ   NOT NULL
);

CREATE INDEX idx_comments_ticket ON comments (ticket_id, created_at);
