CREATE TABLE attachments (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id      BIGINT       NOT NULL REFERENCES tickets (id) ON DELETE CASCADE,
    uploaded_by_id BIGINT       NOT NULL REFERENCES users (id),
    filename       VARCHAR(255) NOT NULL,
    content_type   VARCHAR(100) NOT NULL,
    size           BIGINT       NOT NULL,
    created_at     TIMESTAMPTZ  NOT NULL
);

CREATE INDEX idx_attachments_ticket ON attachments (ticket_id);

-- The bytes live in a separate table so listing attachments never loads the files.
CREATE TABLE attachment_content (
    attachment_id BIGINT PRIMARY KEY REFERENCES attachments (id) ON DELETE CASCADE,
    data          BYTEA NOT NULL
);
